### ISSUE TITLE
uploading big pictures fails badly

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#11]
Uploading a 1.3 MB pictures sends you to a 413 Request Entity Too Large.  Should fail more gracefully.

**Comment by codersquid** [comment]
I suspected an nginx setting or/and a django setting. I replicated the issue with a 2.8MB file, I added client_max_body_size and set it to 10M in our nginx conf and uploaded the file successfully (didn't have a 10M handy). What limit would you like? I just picked 10 out of the air.

**Comment by codersquid** [comment]
If 10M isn't good then we can up it.
