### ISSUE TITLE
Review dashboard is blocked for users who vote -0 or -1

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#111]
http://mail.scipy.org/pipermail/scipy-organizers/2014-April/000377.html

> So I tried voting with a -0 or -1 on a tutorial and now I can't get back
> into the tutorial reviews in my dashboard. I thought it would just refuse
> to work, but it looks like it recorded the vote and now I cannot return to
> the tutorials review site:
> https://conference.scipy.org/scipy2014/reviews/section/tutorials/

**Comment by codersquid** [comment]
@kthyng could you take a look to see if you can view the dashboard?

I have a workaround, and the view ends up looking like this, for example, if someone gave a negative zero vote.
![negzero](https://cloud.githubusercontent.com/assets/529748/2773027/5bf7edcc-ca8d-11e3-89a3-62e087aa7ca8.png)

**Comment by kthyng** [comment]
Yes! It works now!!! (At least on my phone...)

You're the best!

On Tuesday, April 22, 2014, Sheila Miguez notifications@github.com wrote:

> @kthyng https://github.com/kthyng could you take a look to see if you
> can view the dashboard?
> 
> I have a workaround, and the view ends up looking like this, for example,
> if someone gave a negative zero vote.
> [image: negzero]https://cloud.githubusercontent.com/assets/529748/2773027/5bf7edcc-ca8d-11e3-89a3-62e087aa7ca8.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/111#issuecomment-41117937
> .

## 

Kristen M. Thyng
Postdoctoral Research Associate
Department of Oceanography
Texas A&M University
http://kristenthyng.com
