### ISSUE TITLE
Page added to scipy_registration returns 502 Bad Gateway in browser

### ISSUE THREAD

**Issue by polarbeardesign** [scipy-conference/SciPy-2014#114]
https://conference.scipy.org/scipy_registration/admin/registrant_add.php

**Comment by polarbeardesign** [comment]
@codersquid - was looking at http://wildlyinaccurate.com/solving-502-bad-gateway-with-nginx-php-fpm

They recommend changing the listen setting from listen = /var/run/php5-fpm.sock to match the fastcgi_pass location in your Nginx configuration e.g. listen = 127.0.0.1:9000

I check our /etc/php5/fpm/pool.d/www.conf and found:

; Note: This value is mandatory.
listen = /var/run/php5-fpm.sock
;listen = 127.0.0.1:9000

Do you think we can change that  as tehy suggest to see if it fixes the 502 errors? And is 9000 the correct port?

**Comment by aterrel** [comment]
fixed long ago. Was bug with nginx allowed response size.
