### ISSUE TITLE
Program Committee profile option

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#12]
This site looks super cool! Thanks @codersquid @mrterry and @polarbeardesign !
I'm trying to figure out what the workflow will be for the program committee (the people who review abstracts for the conference... many of them will also be authors). 

Since it seems to me that what will be needed is for them to create accounts on the website and then do something like "add a program committee profile". That profile would include things like "areas of expertise" keywords and the number of abstracts they are willing to review. Such a profile would then be approved by @sjsrey and I. Finally, that profile would give them access to whatever abstracts they need to review. Is that right? 

If that's the workflow symposion supports, then this ticket is intended to suggest that such a "program commitee profile" be added to the dashboard and connected to the abstract access... however that happens.

That is, I think this ticket will be complete if a "program committee" option is here on the dashboard so that people can request to be given program committee access:

![image](https://f.cloud.github.com/assets/393899/1847613/08eab2b8-765a-11e3-9a27-891d784de2b9.png)

Let me know what you guys think! Thanks!!

**Comment by stefanv** [comment]
:+1:

**Comment by codersquid** [comment]
It's a good idea, and symposion's Teams/Memberships model might be how to handle this. The _Teams_ panel shows on the same page as _Speaking_. I've created a Program Committee team, along with a couple of others 

superuser dashboard:
![teams](https://f.cloud.github.com/assets/529748/1948603/1a6f9e16-809d-11e3-9e01-bf2b69da31cb.png)

non superuser dashboard:
![unpriv_teams](https://f.cloud.github.com/assets/529748/1948616/11d725e8-809e-11e3-95b4-1ddec8c70fdf.png)

The non super-user account is able to view https://conference-staging.scipy.org/teams/program-committee/ and apply for membership, but it would be better to have it rendered on the dashboard.

I can dig in to the symposion src to see how it decides to render teams on the dashboard.

**Comment by aterrel** [comment]
@codersquid I believe you had this fixed in staging running a command.  Can we get that on prod and added to the fab file (somehow).

**Comment by codersquid** [comment]
Forgot to update this to let you know that it is working in prod now, and I've confirmed with @katyhuff

**Comment by codersquid** [comment]
I will close this when I have documented it well enough for other people to follow the process.

**Comment by codersquid** [comment]
documentation tracked in #66
