### ISSUE TITLE
The schedule team permissions aren't working for some users

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#123]
I set up a schedule team in symposion and assigned permissions for the schedule app to it, but I'm getting reports that some users are unable to edit the schedule.

**Comment by mandli** [comment]
Any movement on getting this fixed?  Matt and I want to start posting the schedule for the BoFs and we are still getting the page not found problem when going through the link provided before:

https://conference.scipy.org/scipy2014/schedule/bofs/edit/

**Comment by codersquid** [comment]
Hi @mandli I'm finding it a lot easier to generate the schedule based on a csv file rather than using the grid editor. The csv looks like this [bofs.csv](https://github.com/scipy-conference/SciPy-2014/blob/master/data/bofs.csv) and you can edit a bof sheet in the google doc I shared (email me for the url). 

This is clunky, but do you find it reasonable enough for now?

**Comment by mandli** [comment]
Thanks for your work on this, I think this is great as it should be easy to modify.  Send me the URL and Matt and I can get to work with the scheduling.
