### ISSUE TITLE
have a schedule page for posters

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#125]
We want to give people a list of posters with links to the details like we do in the schedule grid.

This isn't currently automagic from symposion because we've bucketed poster proposals in with talks. We will figure something out.

**Comment by codersquid** [comment]
@katyhuff 

How much work would you like to do for this?  First, someone needs to go through all the accepted proposals to make a list of the ones that are accepted as posters. I can help automate that a bit by writing some quick code to list out the list of all the talks for you.

There are two approaches I can think of off the top of my head once you have the list.
- We can do things manually and generate a page from the list.
- We can do things so that posters are treated the same way as the other types so that we get a dynamically generated schedule grid for them.

I was interested in the latter so I threw together some code (unreviewed) so that we have parts in place to do that -- but it would take some additional work. We'd need to write some code that takes the list of accepted posters so that we can create PosterProposals based on the TalkPosterProposals.

I'll append the sql  (unreviewed) for adding the table or dropping it in case someone wants to pick up this task and run with it.

```
BEGIN;
use scipy2014;
CREATE TABLE `proposals_posterproposal` (
    `proposalbase_ptr_id` integer NOT NULL PRIMARY KEY,
    `topic_track` varchar(50) NOT NULL,
    `domain_symposium` varchar(50) NOT NULL
)
;
ALTER TABLE `proposals_posterproposal` ADD CONSTRAINT `proposalbase_ptr_id_refs_id_3df7126d` FOREIGN KEY (`proposalbase_ptr_id`) REFERENCES `proposals_proposalbase` (`id`);
COMMIT;
```

```
BEGIN;
DROP TABLE `proposals_posterproposal`;
COMMIT;
```

**Comment by katyhuff** [comment]
On Sat, May 17, 2014 at 8:45 AM, Sheila Miguez notifications@github.comwrote:

> @katyhuff https://github.com/katyhuff
> 
> How much work would you like to do for this? First, someone needs to go
> through all the accepted proposals to make a list of the ones that are
> accepted as posters.

All of the ones currently listed as "standby" are the posters. Does that
help?

> I can help automate that a bit by writing some quick code to list out the
> list of all the talks for you.
> 
> There are two approaches I can think of off the top of my head once you
> have the list.
> - We can do things manually and generate a page from the list.
> - We can do things so that posters are treated the same way as the
>   other types so that we get a dynamically generated schedule grid for them.
> 
> I was interested in the latter so I threw together some code (unreviewed)
> so that we have parts in place to do that -- but it would take some
> additional work. We'd need to write some code that takes the list of
> accepted posters so that we can create PosterProposals based on the
> TalkPosterProposals.
> 
> I'll append the sql (unreviewed) for adding the table or dropping it in
> case someone wants to pick up this task and run with it.
> 
> BEGIN;
> use scipy2014;
> CREATE TABLE `proposals_posterproposal` (
>     `proposalbase_ptr_id` integer NOT NULL PRIMARY KEY,
>     `topic_track` varchar(50) NOT NULL,
>     `domain_symposium` varchar(50) NOT NULL
> )
> ;
> ALTER TABLE `proposals_posterproposal` ADD CONSTRAINT `proposalbase_ptr_id_refs_id_3df7126d` FOREIGN KEY (`proposalbase_ptr_id`) REFERENCES `proposals_proposalbase` (`id`);
> COMMIT;
> 
> BEGIN;
> DROP TABLE `proposals_posterproposal`;
> COMMIT;
> 
> I don't think I have access to the db?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/125#issuecomment-43410315
> .

## 

http://katyhuff.github.com

**Comment by codersquid** [comment]
On Sat, May 17, 2014 at 12:34 PM, Katy Huff notifications@github.comwrote:

> On Sat, May 17, 2014 at 8:45 AM, Sheila Miguez notifications@github.comwrote:
> 
> > @katyhuff https://github.com/katyhuff
> > 
> > How much work would you like to do for this? First, someone needs to go
> > through all the accepted proposals to make a list of the ones that are
> > accepted as posters.
> 
> All of the ones currently listed as "standby" are the posters. Does that
> help?

Yes!

> I don't think I have access to the db?

No worries! I was leaving notes for tech chairs.

## 

shekay@pobox.com

**Comment by codersquid** [comment]
@katyhuff here, I did something a lot simpler, but it will depend on whether we leave posters in a standby state, which I don't know what all the consequences will be. I notice one consequence is that the poster presentation doesn't show up on the author page.

Anyway, this new view shows something like below. What do you think?

Some problems
- it is listing content based on the Proposal and not a Presentation object. Authors can change proposals.
- We still have name problems due to the database encoding. a pessimism bias could say that we'll fix the data in on table and forget to fix it in the tables that render this view. Which will be annoying, but no puppies will die.

![posterlist](https://cloud.githubusercontent.com/assets/529748/3005926/b64ab5f8-ddfb-11e3-9f78-7e586b12e282.png)

**Comment by katyhuff** [comment]
On Sat, May 17, 2014 at 12:47 PM, Sheila Miguez notifications@github.comwrote:

> @katyhuff https://github.com/katyhuff here, I did something a lot
> simpler, but it will depend on whether we leave posters in a standby state,

Oh, well, I don't have any particular reason to leave them in standby
state. I just did that because there was no "accepted as a poster" option.
If they need to be in the accepted state, we can do that too, as long as we
make sure  the list is preserved. The "undecided" ones are either rejected
or un-confirmed poster-presenting attendees.

> which I don't know what all the consequences will be. I notice one
> consequence is that the poster presentation doesn't show up on the author
> page.
> 
> Anyway, this new view shows something like below. What do you think?

That looks great!!

> Some problems
> - it is listing content based on the Proposal and not a Presentation
>   object. Authors can change proposals.
> 
> Hm. I see. Well.. that seems alright. It shouldn't cause a problem.
> - We still have name problems due to the database encoding.
> 
> I see  - yeah.yuck
> - a pessimism bias could say that we'll fix the data in on table and
>   forget to fix it in the tables that render this view. Which will be
>   annoying, but no puppies will die.
> 
> i'm not sure I understand this statement. But, I trust you.
> 
> [image: posterlist]https://cloud.githubusercontent.com/assets/529748/3005926/b64ab5f8-ddfb-11e3-9f78-7e586b12e282.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/125#issuecomment-43422414
> .

## 

http://katyhuff.github.com

**Comment by codersquid** [comment]
Oh, well, I don't have any particular reason to leave them in standby

> state. I just did that because there was no "accepted as a poster" option.

a fortuitous circumstance!

> If they need to be in the accepted state, we can do that too, as long as
> we
> make sure the list is preserved. The "undecided" ones are either rejected
> or un-confirmed poster-presenting attendees.

Yes, if we leave it this way I would change the view to filter out based on
whether the author confirmed they wanted to talk.

> which I don't know what all the consequences will be. I notice one
> 
> > consequence is that the poster presentation doesn't show up on the
> > author
> > page.
> > 
> > Anyway, this new view shows something like below. What do you think?
> 
> That looks great!!

I discovered that all of the other schedule types also have a list option.
So it was a nice journey through the symposion code.

> > - We still have name problems due to the database encoding.
> > 
> > I see - yeah.yuck

yeah, I just opened an issue for changing hte encoding and cleaning up
author names.

> > - a pessimism bias could say that we'll fix the data in on table and
> >   forget to fix it in the tables that render this view. Which will be
> >   annoying, but no puppies will die.
> > 
> > i'm not sure I understand this statement. But, I trust you.

I like putting on a hat of pessimism and imagining all the ways in which the
system will fail. including having us clean up one part of the database
while forgetting to clean up the other.

bwahaha we are all doomed. :)

## 

shekay@pobox.com

**Comment by codersquid** [comment]
I made some changes to list the posters here https://conference.scipy.org/scipy2014/posters/ based on the spreadsheet of posters we have (which I've checked in as data/posters/csv).

**Comment by codersquid** [comment]
We've got the posters page and a link from the schedule menu now.
