### ISSUE TITLE
color code schedule grid

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#133]
I used a color-picker to sample colors from the schedule in google docs, and the results are not as good as they can be. The main tracks are readable, but some of the minisymposia are difficult to read.

I can wing picking something else, but if someone wants to pick up the issue I don't mind.

background

The schedule grid is generated so that you can define classes to apply to a grid on the schedule.

```
<td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
```

I've created SlotKinds in the db that correspond to the tracks, etc.

This css snippet goes in 2014.css generates the example screenshots. I'm not checking it in, since I don't like the result, but I am providing it for explanatory purposes.

```
/* schedule grid tracks and minisymposion styles
 *
 * .slot-<kind> corresponds to the label field of SlotKind
 *
 * hard coded, meh.
 */

/*
 * td.slot, td.slot.slot-plenary, td.slot.slot-break are in site.css
 */

/* example style from last year */
/*
.astro {
  background-color: #C27BA0;
  border: 1px solid #666;
  padding: 0 4px  
}
*/

.slot-astro {
  background-color: #C27BA0;
}
.slot-geophysics {
  background-color: #7F6000;
}
.slot-geospatial {
  background-color: #D9D2E9;
}
.slot-bio {
  background-color: #F6B26B;
}
.slot-digisocial {
  background-color: #D9EAD3;
}
.slot-engineering {
  background-color: #FFF2CC;
}
.slot-General {
  background-color: #CFE2F3;
}
.slot-imaging {
  background-color: #6AA84F;
}
.slot-Keynote {
  background-color: #FFE599;
}
.slot-edu {
  background-color: #EAD1DC;
}
.slot-Welcome {
  background-color: #FFE599;
}
.slot-BOFs {
  background-color: #EA9999;
}
.slot-social {
  background-color: #FFFF00;
}
.slot-wssspe {
  background-color: #F1C232;
}

/* may or may not need colors for these
.slot-plenarybreak {
  background-color: #FFFFFF;
}
.slot-Break {
  background-color: #FFFFFF;
}
.slot-lightning {
  background-color: #FFFFFF;
}
.slot-Posters {
  background-color: #FFFFFF;
}
.slot-special {
  background-color: #FFFFFF;
}
.slot-tutorial {
  background-color: #FFFFFF;
}
.slot-bof {
  background-color: #FFFFFF;
}
.slot-sprint {
  background-color: #FFFFFF;
}
*/
```

![colors2](https://cloud.githubusercontent.com/assets/529748/3306201/b5ff1e7e-f65e-11e3-8e0f-de42f3286abd.png)
![colors](https://cloud.githubusercontent.com/assets/529748/3306200/b5feca5a-f65e-11e3-8504-1da0de4b00e3.png)

**Comment by sjsrey** [comment]
hi sheila,

there was no real thought into the colors that we used in the google doc -
they were meant just for internal consumption and not really presentation
(you don't want me picking colors for that believe me).

On Tue, Jun 17, 2014 at 1:40 PM, Sheila Miguez notifications@github.com
wrote:

> I used a color-picker to sample colors from the schedule in google docs,
> and the results are not as good as they can be. The main tracks are
> readable, but some of the minisymposia are difficult to read.
> 
> I can wing picking something else, but if someone wants to pick up the
> issue I don't mind.
> 
> background
> 
> The schedule grid is generated so that you can define classes to apply to
> a grid on the schedule.
> 
> <td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
> 
> I've created SlotKinds in the db that correspond to the tracks, etc.
> 
> This css snippet goes in 2014.css generates the example screenshots. I'm
> not checking it in, since I don't like the result, but I am providing it
> for explanatory purposes.
> 
> /\* schedule grid tracks and minisymposion styles
>  *
> - .slot-<kind> corresponds to the label field of SlotKind
>   *
> - hard coded, meh.
>   */
> 
> /*
> - td.slot, td.slot.slot-plenary, td.slot.slot-break are in site.css
>   */
> 
> /\* example style from last year _/
> /_
> .astro {
>   background-color: #C27BA0;
>   border: 1px solid #666;
>   padding: 0 4px
> }
> */
> 
> .slot-astro {
>   background-color: #C27BA0;
> }
> .slot-geophysics {
>   background-color: #7F6000;
> }
> .slot-geospatial {
>   background-color: #D9D2E9;
> }
> .slot-bio {
>   background-color: #F6B26B;
> }
> .slot-digisocial {
>   background-color: #D9EAD3;
> }
> .slot-engineering {
>   background-color: #FFF2CC;
> }
> .slot-General {
>   background-color: #CFE2F3;
> }
> .slot-imaging {
>   background-color: #6AA84F;
> }
> .slot-Keynote {
>   background-color: #FFE599;
> }
> .slot-edu {
>   background-color: #EAD1DC;
> }
> .slot-Welcome {
>   background-color: #FFE599;
> }
> .slot-BOFs {
>   background-color: #EA9999;
> }
> .slot-social {
>   background-color: #FFFF00;
> }
> .slot-wssspe {
>   background-color: #F1C232;
> }
> 
> /\* may or may not need colors for these
> .slot-plenarybreak {
>   background-color: #FFFFFF;
> }
> .slot-Break {
>   background-color: #FFFFFF;
> }
> .slot-lightning {
>   background-color: #FFFFFF;
> }
> .slot-Posters {
>   background-color: #FFFFFF;
> }
> .slot-special {
>   background-color: #FFFFFF;
> }
> .slot-tutorial {
>   background-color: #FFFFFF;
> }
> .slot-bof {
>   background-color: #FFFFFF;
> }
> .slot-sprint {
>   background-color: #FFFFFF;
> }
> */
> 
> [image: colors2]
> https://cloud.githubusercontent.com/assets/529748/3306201/b5ff1e7e-f65e-11e3-8e0f-de42f3286abd.png
> [image: colors]
> https://cloud.githubusercontent.com/assets/529748/3306200/b5feca5a-f65e-11e3-8504-1da0de4b00e3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-conference/SciPy-2014/issues/133.

## 

Sergio (Serge) Rey
Professor, School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
Arizona State University
http://geoplan.asu.edu/rey

Editor, International Regional Science Review
http://irx.sagepub.com

**Comment by polarbeardesign** [comment]
I may take a crack at it later  - if no one beats me to it.

Jim Ivanoff
www.polarbeardesign.net

**Comment by codersquid** [comment]
@sjsrey same for me. I keep bookmarks to a couple of tools for helping me to pick colors, but I always need a sanity check.
- http://leaverou.github.io/contrast-ratio/
- http://paletton.com/

**Comment by codersquid** [comment]
I went ahead and added some colors that are shades of blue and some adjacent blueish things on a color wheel. I'm going to close this out, but I would not at all mind if someone wanted to make a PR with a better color scheme.
