### ISSUE TITLE
fix domain symposia

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#14]
The current domain symposia options are from last years.  Update them on staging and in the fixtures.

**Comment by mrterry** [comment]
@aterrel what are our mini-symposia this year?

**Comment by katyhuff** [comment]
@mrterry : @sjsrey and I are very close to finalizing this. I'll post here when those are concrete.

**Comment by katyhuff** [comment]
Astronomy and Astrophysics
Bioinformatics
Geophysics
Vision, Visualization, and Imaging
Digital Social Sciences 
Engineering
