### ISSUE TITLE
Matthew Russell not coming

### ISSUE THREAD

**Issue by davclark** [scipy-conference/SciPy-2014#145]
Hi @codersquid, @katyhuff says if I get this to you quickly, you might be able to make these changes.

In short, Jul 10 has a no-show. So please:
- [x] move "Mapping Networks of Violence" with 
  Evan Misshula, Sheyla Delgado to the beginning of that block (2:15)...
- [ ] and let them know they can go longer if they wish (I can contact them if you make the schedule change)
- [x] Adjust the talks in the late afternoon by Seb Benthall and Jon Riehl to be 20 minutes each, followed by a 20 minute "Social Science & Privacy Panel"

**Comment by codersquid** [comment]
Hi @davclark, I rearranged the schedule. Give the authors a heads up about the extra time.
