### ISSUE TITLE
Changes to Posters

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#146]
So, I sent an email last night to make sure that the presenters had sufficient instructions and had checked their presence on the schedule. This, of course, means there will be some last minute tweaks as they respond saying "nevermind" and "I'm not on the list!". I'm going to record them in this issue and maybe they can be fixed all in one go some time in the next few days? Should I just change the CSV in the google docs, @codersquid ? Let me know what the right workflow should be. 

So far the following changes need to be made : 
- Jeff Jones (164) Should be deleted from posters. Turns out he can't come.
- Michael Nowak (77) Should be added to posters (I think this one is entirely my fault. I think he confirmed only to me and I didn't record his confirmation.)

**Comment by codersquid** [comment]
Change the CSV in the Posters doc, then give me a heads up when you are done.

**Comment by katyhuff** [comment]
Will do. Thanks!

**Comment by katyhuff** [comment]
Ok, I think that's all the drama that's going to arise. The csv is changed. It's just the one change, replacing 164 with 77. 

Sorry, I know this breaks things. I hope you won't hesitate to blame me when folks get disgruntled.

**Comment by codersquid** [comment]
This one doesn't break all the links in the schedule -- it's just a quick and dirty thing I made to generate a page with poster info. no worries!

**Comment by katyhuff** [comment]
Thanks !!!!!!!

**Comment by codersquid** [comment]
gotcha. check out the posters link now. https://conference.scipy.org/scipy2014/posters/

**Comment by katyhuff** [comment]
Perfect! Thanks so much!
