### ISSUE TITLE
Talk Slots too Short

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#147]
As noted by @astrofrog and @asmeurer : the final morning talk slots on all three days of the conference should go from 11:45-12:15. As it is, they go from 11:45-12:00. 

These are the affected talks:
- https://conference.scipy.org/scipy2014/schedule/presentation/1682/
- https://conference.scipy.org/scipy2014/schedule/presentation/1683/
- https://conference.scipy.org/scipy2014/schedule/presentation/1684/
- https://conference.scipy.org/scipy2014/schedule/presentation/1706/
- https://conference.scipy.org/scipy2014/schedule/presentation/1707/
- https://conference.scipy.org/scipy2014/schedule/presentation/1708/
- https://conference.scipy.org/scipy2014/schedule/presentation/1718/
- https://conference.scipy.org/scipy2014/schedule/presentation/1719/
- https://conference.scipy.org/scipy2014/schedule/presentation/1720/

@codersquid I think I can just fix it by changing the talk slot definitions, so I'm going to do that. Please tell me if I break something!

**Comment by codersquid** [comment]
@katyhuff hopefully that works. when you've got that done let me know and I'll help check.

**Comment by asmeurer** [comment]
At best you might notify the speakers that their talks are not really that short. I was a little worried about it myself when I saw this.

**Comment by katyhuff** [comment]
Ok, so I changed the slots in the admin section by going in, finding them, changing the end time, and saving, but it's not being reflected on the schedule. 
![image](https://cloud.githubusercontent.com/assets/393899/3457961/1e2b2372-01fd-11e4-8473-6998591f088e.png)

**Comment by katyhuff** [comment]
@asmeurer I'll send an email. Good call.

**Comment by asmeurer** [comment]
Didn't somebody say on the organizers list that the schedule has to be rebuilt each time a change is made or something like that?

**Comment by katyhuff** [comment]
Though, hey, now the individual talk pages look right : 

![image](https://cloud.githubusercontent.com/assets/393899/3458000/6c70a976-01fd-11e4-8ded-b866309b2ef9.png)

**Comment by codersquid** [comment]
could just be the cache taking a bit to update

**Comment by katyhuff** [comment]
@asmeurer yeah, @codersquid has to rebuild everything when we actually move talks around. Hopefully this doesn't require that. 

Thanks @codersquid !

**Comment by katyhuff** [comment]
Whee! It worked. All better now. Closing this issue. (I'll send emails, @asmeurer , thanks for your help!)

**Comment by asmeurer** [comment]
You broke all the links to the talks.

**Comment by katyhuff** [comment]
really? it works for me. . . could you be more specific.

On Wed, Jul 2, 2014 at 2:30 PM, Aaron Meurer notifications@github.com
wrote:

> You broke all the links to the talks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-conference/SciPy-2014/issues/147#issuecomment-47839515
> .

## 

http://katyhuff.github.com

**Comment by katyhuff** [comment]
@asmeurer - which links?
From the schedule, the links go straight to the talks. 

This, for example:
![image](https://cloud.githubusercontent.com/assets/393899/3462813/0dfcb882-0232-11e4-8da1-46e9d8f9584e.png)

Goes to your individual talk page : 
https://conference.scipy.org/scipy2014/schedule/presentation/1708/

Does that not happen for you?

Are you talking about how the urls have changed in the last few weeks? If so, please see the unrelated discussion about that on the listhost http://mail.scipy.org/pipermail/scipy-organizers/2014-July/000698.html .

**Comment by katyhuff** [comment]
@asmeurer - if you can confirm or deny the details of this behavior you've reported, that would put my mind at ease. Thanks.

**Comment by asmeurer** [comment]
Rather, the links changed. Any links to talks that were published before this fix now 404.

**Comment by asmeurer** [comment]
Example https://twitter.com/ContinuumIO/status/483701915642232833

**Comment by asmeurer** [comment]
I didn't see this discussion. The link to my talk that I had open in my browser changed (I think) after you made this fix, which is why I think it is related. I'm not 100% positive if it is, though.

**Comment by asmeurer** [comment]
Ah, apparently I did see that discussion (it was the one I referenced earlier in this PR), but I didn't catch the bit where the links break each time you regenerate the schedule.

**Comment by katyhuff** [comment]
Right, ok, phew. The changing links were unrelated to this particular change. 

The links at the top of this issue were the links that existed before I made this change. They remain the same after. 

But, yes, the links have been changing. Sad news. I think sheila is thinking about ways to fix it with a bitly script.
