### ISSUE TITLE
document how to add reviewers without also requiring superuser privs

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#19]
making this issue so we remember to document the process once we know how to do it.

**Comment by codersquid** [comment]
I also posted this as a question to the symposion mailing list.

**Comment by katyhuff** [comment]
Just checking -> this is so that Serge and I can point reviewers at specific abstracts?

**Comment by codersquid** [comment]
@katyhuff, I am not sure, it is something @mrterry mentioned during the last tech meeting and I jotted this issue down hastily. It might be.

Anyway, here's an answer from the symposion mailing list. Is it helpful? I can try it later today or this week.

> Sorry for the delay in replying...
> 
> Basically here are the steps.
> 1. set up your Section(s) and ProposalSection(s)
> 2. run the create_review_permissions management command. This will create a django permission "can_review_{section_slug}" for each section.
> 3. create a Team (or Teams if different sets of people are reviewing different sections)
> 4. in the admin, on the detail page for the team, add the "can_review_{section_slug}" under "permissions" for whatever sections you want that team to be able to review
> 5. use the normal site UI to manage team membership
> 
> Let me know if any of these steps need further elaboration.

**Comment by katyhuff** [comment]
I see. I guess it's probably helpful. I'm not sure what a section is or a proposal section. If those correspond to the abstract submissions to the main tracks or minisymposia, then, that definitely would be the thing. 

As it is, though, there is not an apparent place to submit a talk abstract ( see issue #22 )... so my ability to assign  those abstracts among the reviewers is currently a bit moot. That is - Issue #22 is more urgent than my ability to assign reviewers.

**Comment by katyhuff** [comment]
(also, thanks @codersquid !!! )

**Comment by codersquid** [comment]
I'll work on this.

**Comment by codersquid** [comment]
I ran the django command that Jacob  mentioned, which added some new permissions.

```
$ ./manage.py create_review_permissions
reviews | reviews | Can review Tutorials
reviews | reviews | Can manage Tutorials
reviews | reviews | Can review Talks and Posters
reviews | reviews | Can manage Talks and Posters
reviews | reviews | Can review Birds of a Feather
reviews | reviews | Can manage Birds of a Feather
reviews | reviews | Can review Sprints
reviews | reviews | Can manage Sprints
```

For an example, I added two **Teams**, _Super reviewers_ and _Talk reviewers_, and added a couple of **Memberships** for a couple of my accounts to check that I had differential permissions based on the teams. That worked.

I should figure out how to automate permissions creation for when we set up production.

**Comment by codersquid** [comment]
documentation tracked in #66
