### ISSUE TITLE
hotel rates are absent

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#21]
Fill in lodging rate.

**Comment by nrrb** [comment]
![screenshot from 2014-01-16 17 50 19](https://f.cloud.github.com/assets/486230/1936344/073bedbc-7f09-11e3-8c52-fa14f7e19676.png)

They appear to be static values here:
https://github.com/scipy-conference/SciPy-2014/blob/master/scipy2014/templates/venue/lodging.html#L18

**Comment by aterrel** [comment]
The room rate is $121 plus tax

**Comment by mrterry** [comment]
done in #33
