### ISSUE TITLE
Need place for abstract submissions

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#22]
In the Speaker Profile (which looks great!), I noticed we can submit proposals for everything _except_ abstract submissions. I don't mean to bug you, as I assume adding that is in the plan, but wanted to submit this issue in case it was simply missed. 

If it is in the plan, can I ask what the status is for that? Is there any information you folks ( @mrterry , @codersquid , @polarbeardesign ) need from me to move forward on that? The call for proposals can't happen until it's live.

**Comment by codersquid** [comment]
It works properly locally for me. I'm going to update staging and see if this got fixed in a recent commit.

**Comment by katyhuff** [comment]
What do you mean by properly?
This is what I see : 
![image](https://f.cloud.github.com/assets/393899/1926917/dea528ac-7e4d-11e3-9f16-32db4e834933.png)

**Comment by katyhuff** [comment]
the above has no place for a talk abstract.

**Comment by codersquid** [comment]
On my laptop, locally, I get a link for talks, but on staging, I don't -- and staging is behind a lot of commits.

**Comment by katyhuff** [comment]
Ah! I see. Great!!

**Comment by codersquid** [comment]
Darn, I updated staging to the latest master and it still doesn't show the link. I will continue investigating

**Comment by katyhuff** [comment]
good luck! thanks!!

**Comment by codersquid** [comment]
woohoo. reproduced locally by dumpdata from the staging site and loaddata to my local setup.

**Comment by katyhuff** [comment]
:+1:

**Comment by codersquid** [comment]
@katyhuff try now. I have talk/poster showing up. In Admin I changed the _closed_ attribute from _yes_ to _no_. _unknown_ also allows it to be listed.

I'll add this to my notes of things we should document. I've got a wiki page for now.

**Comment by katyhuff** [comment]
great!

**Comment by katyhuff** [comment]
Yep, works for me. I deem this closed. Thanks @codersquid !
