### ISSUE TITLE
responsive layout wraps strangely

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#26]
@polarbeardesign 
The boxes on the front page wrap strangely for narrow-ish screens.
![screen shot 2014-01-16 at 8 34 57 am](https://f.cloud.github.com/assets/528022/1932455/438a8a40-7ecc-11e3-90ac-3f5f5afeb6fb.png)

**Comment by polarbeardesign** [comment]
setting the box width to 29% - currently at 30% - seemed to fix it, but that was one of those changes I mentioned that didn't show up in the update. (static css file).

**Comment by codersquid** [comment]
That's me, I forgot to run collectstatic. I'll go run that now.

**Comment by codersquid** [comment]
I just ran it, how about now?

**Comment by polarbeardesign** [comment]
works in my single browser test
:-)

**Comment by mrterry** [comment]
works for me.  closing.

that said, it would be nice if we had a more mobile friendly layout.  you have to do a bit of zooming to read anything on a phone.
