### ISSUE TITLE
sponsors do not automatically show up in sponsors page

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#29]

**Comment by mrterry** [comment]
the issue is actually that staff added sponsors do not have pictures.  the view for the sponsors page seems to need images.

**Comment by mrterry** [comment]
sponsor image upload does not seem to work

**Comment by mrterry** [comment]
there are three components of this.
1) our nginx config was bad (fixed)
2) file permissions for upload files are bad (vixed)
3) the template tag {% thumbnail %} does not render

**Comment by mrterry** [comment]
this is an installing PIL / pillow bug.

**Comment by aterrel** [comment]
This has been fixed
