### ISSUE TITLE
are keynotes just talks or should we add a new type?

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#31]

**Comment by katyhuff** [comment]
Keynotes are pre-arranged talks by special invitees, so people shouldn't be allowed submit proposed keynotes. That said, the keynotes should end up in the program... so... I don't know if that answers the question you need answered. Does that help?

**Comment by codersquid** [comment]
Yes, It does. I was wondering from the point of view of supporting committee workflows. It sounds like we wouldn't want to add a new type, because that would show up as an option for submissions. But then, to handle having keynotes show up on the schedule, we'd probably add them as talks and then go through the approve/publish workflow.

I think it's a use case we should test when we go through the review workflow in case there is something the tech-chairs need to do to handle keynotes as a special case.

**Comment by katyhuff** [comment]
ok. Sounds like a reasonable plan to me. Thanks!! :)
