### ISSUE TITLE
Sponsor logo display

### ISSUE THREAD

**Issue by polarbeardesign** [scipy-conference/SciPy-2014#37]
Logos not showing up when using

{% include "sponsorship/_vertical_by_level.html" %}

fm http://symposion.readthedocs.org/en/latest/sponsorship.html#template-tags

to display sponsors in the sites sidebar. Maybe the doc is outdated?

**Comment by mrterry** [comment]
I added (perhaps mistakenly) content in the sidebar.  I'll look into this.

**Comment by aterrel** [comment]
Looks like this is fixed. with #60
