### ISSUE TITLE
Sponsor email

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#44]
An email should be sent to the sponsorship chairs when someone uses the sponsor features.

**Comment by brettrmurphy** [comment]
I "applied" and could see the email address in the form was mine. I did not add any attachments on the second page of the application and just saved it. It says its "awaiting approval". No email was sent though it seems?

**Comment by codersquid** [comment]
Is this still an issue, or was mail sent after we added the cron job? If the root cause was the missing cron job, then when #46 is resolved we can close this.

**Comment by aterrel** [comment]
@brettrmurphy Waiting for you to verify this is still a bug.

**Comment by brettrmurphy** [comment]
I still have not received a notice. It still says it is "waiting approval"
in there.

-- Brett

Brett Murphy
Enthought, Inc.
bmurphy@enthought.com
512-536-1057

**Comment by aterrel** [comment]
I'm deleting. Try to resubmit.
