### ISSUE TITLE
Announce list form not shown on front page

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#45]
The front page doesn't show the form for signing up to the mailing list.  Since the page is using https to serve and the form is pulling http request, chrome marks it as unsafe.  

Should try to have a https form there.

**Comment by mrterry** [comment]
the form gets filled in by some 3rd party js that we run on the front page.  i would prefer we build the form ourselves and submit it to whomever we're supposed to.  do you know who at enthought controls the email list account?

**Comment by mrterry** [comment]
ps.  i've started looking at mailgun for managing our mailing lists.  it looks nifty

**Comment by codersquid** [comment]
TODOs from the meeting this morning -- we compared mailgun and mailchimp, and mailchimp is friendlier for people with all levels of experience. We decided to go with that. I will set it up.

**Comment by aterrel** [comment]
Lets just point the button to the mailchimp hosted form at http://eepurl.com/N50Lb

**Comment by aterrel** [comment]
I went ahead and updated this.  We can make the form nicer later =P

**Comment by aterrel** [comment]
We agreed today that this was "Good Enough" which Alex Martelli tells me is "Better than Perfect".
