### ISSUE TITLE
Remove [Local] in prod site title

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#51]
conference.scipy.org/scipy2014 has [Local] in the title.  This should be removed.

**Comment by codersquid** [comment]
Set SITE_ID to the prod site. We need deploy to be updated to handle that as well.

**Comment by mrterry** [comment]
I thought I fixed this.

**Comment by mrterry** [comment]
i have SITE_ID=3 in prod_settings.py  I just re-deployed the site and [local] is gone

**Comment by polarbeardesign** [comment]
I seem to have reverted this with my last update. I don't see that setting in prod_settings.py - is that the correct file? Can't seem to find it in commits either.

I see similar in scipy2014/settings_gondor.py and scipy2014/settings.py - Is the setting in scipy2014/settings.py?

**Comment by polarbeardesign** [comment]
Hmm - now it's disappeared. Maybe a cache issue

**Comment by ghost** [comment]
doh.  i have this in my local prod_settings.py, but have not committed it
