### ISSUE TITLE
Move current sponsors link to top of sponsors dropdown

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#53]
![screen shot 2014-02-02 at 11 11 17 am](https://f.cloud.github.com/assets/30583/2060729/295bfcbc-8c2d-11e3-96e9-9e5a97daa588.png)

Put "SciPy 2014 Sponsors" as the top link.

**Comment by polarbeardesign** [comment]
moved to top, removed [local]
