### ISSUE TITLE
Talk Submissions Don't Preserve Track

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#54]
Currently, submitters can select a track and/or minisymposium when submitting a talk abstract

![image](https://f.cloud.github.com/assets/393899/2105396/b57b1640-8f8b-11e3-9023-eb3b68dca300.png)

However, that track selection does not appear when I, as a reviewer, go to look at the submission. 

![image](https://f.cloud.github.com/assets/393899/2105399/d5f68198-8f8b-11e3-9940-350b9130af5c.png)

**Comment by aterrel** [comment]
@mrterry Is this an issue with the review model?  If not please reassign.

**Comment by katyhuff** [comment]
whoops erroneous close

**Comment by katyhuff** [comment]
I was just trying to comment and accidentally closed the issue (this happens to me way too often). 

I just wanted to comment that there is a little urgency about the first half of this issue. Namely, is the track information being saved?

if we could just determine whether or not this information is being saved in the database when a submission happens, then that would be great for now. That is, as long as submissions happening right now are captured completely, then we can deal with retrieving that information for the reviewers a little later.

**Comment by codersquid** [comment]
I checked in the admin and the track information is being saved. I'm looking through symposion code to see what is going on with the templates.

**Comment by codersquid** [comment]
I add custom template, https://github.com/scipy-conference/SciPy-2014/commit/99ddd7a7d38fb1b6bd5b14dda291143329a3a87e

Locally the text shows up on Proposal Details, but it doesn't display properly in Staging. Staging is showing a number rather than the descriptive text.

Here's the diff from the symposion template

```
$ diff scipy2014/templates/proposals/_proposal_fields.html ~/repos/scipystuff/symposion/symposion/templates/proposals/_proposal_fields.html 
8c8
<     <dd>{{ proposal.get_topic_track_display }}&nbsp;</dd>
---
>     <dd>{{ proposal.track }}&nbsp;</dd>
13,15d12
<     <dt>{% trans "Domain Symposium" %}</dt>
<     <dd>{{ proposal.get_domain_symposium_display }}&nbsp;</dd>
< 
```

**Comment by codersquid** [comment]
I need to switch to testing out the schedule functionality, and I hope this can be picked up by someone while I work on that. I think it is less urgent now that we know the info is stored but still would be good to have when people start reviewing.

**Comment by katyhuff** [comment]
Hi folks. Reviews start in one week! (time flies!)
So - we need this track information to be available to the reviewers asap.

@polarbeardesign, @mrterry, @codersquid, @aterrel : Anything we can do to help?

**Comment by aterrel** [comment]
Well depends if you want to start learning django =P

**Comment by katyhuff** [comment]
:) Maybe I'll get around to that in time for next year...

**Comment by katyhuff** [comment]
Serge and I are beginning to try to assign abstracts to reviewers.
Assigning a paper to the proper reviewer requires simultaneous knowledge of three things: The desired track, the desired domain-symposium, and the ID number. Ideally, the title and author would be available as well, but they're not _absolutely_ necessary.

It would be perfect, if, for example, the Category section of the review dashboard were not blank. If it were, instead, two columns (Domain and Track) holding the requested Domain symposium and Track names, that would be great. The current review dashboard is lovely, and very very close to having everything we need:

![image](https://cloud.githubusercontent.com/assets/393899/2545112/90f1b4e8-b60d-11e3-88d5-bb4b15879711.png)

Is it possible to add track and domain columns there in the next three days?

If not, since the main database holds this info, can it at least be downloaded as a CSV? As is, this is the interface Serge and I have for viewing that database:

![image](https://cloud.githubusercontent.com/assets/393899/2545099/5d1e3786-b60d-11e3-99c7-42f3c803711b.png)

(also, sorry, I butterfingered this issue and closed it a couple days ago. it's open again... my bad. I really wish "comment" were further away from "close and comment")

**Comment by codersquid** [comment]
@katyhuff I'll take a look at it.
I can make the admin look better, regardless of what I do with the template.

I'll also look in to the export_as_csv sympsosion action -- I see that it exists in the symposion code base, but haven't tried using it yet.

**Comment by katyhuff** [comment]
Great! Thanks so much!!
(btw, Potentially more pressing at this exact hour is #96 relating to the diversity financial aid application . )

However, it would be awesome if you could look at this program committe review dashboard thing. The export as csv button at the top of the dashboard works, but only includes the stuff visible in the table, so, for me, it has an empty column labeled "Category".

**Comment by codersquid** [comment]
@katyhuff I deployed a tiny change so that the admin view of proposals is better.

**Comment by katyhuff** [comment]
Thanks a ton @codersquid !

**Comment by katyhuff** [comment]
Closing.

**Comment by codersquid** [comment]
Did you mean to close this? The actual view doesn't have the category listed

**Comment by katyhuff** [comment]
Perfect!!!
