### ISSUE TITLE
Editing Talk Submission Info

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#55]
In the submission form for abstracts, there isn't a lot of information about what we want. That's fine, but I'd love to either link to the call for abstracts or add a more detailed description of what we're hoping folks will submit. In order to do this, am I supposed to click the "Edit This Content" button? I'm worried I'll break something if I do that. 

![image](https://f.cloud.github.com/assets/393899/2105416/28c95fb2-8f8c-11e3-8cb8-d25dd752afa4.png)

**Comment by aterrel** [comment]
We have conference-staging.scipy.org/scipy2014 for playing around. Feel free to try it out there and see if it does what you want.

**Comment by katyhuff** [comment]
That site doesn't seem to behave in the same way (that is, I don't have the edit button.)

**Comment by codersquid** [comment]
Different database in staging. Maybe we could copy from prod.

**Comment by aterrel** [comment]
@codersquid Yes, please do.

**Comment by katyhuff** [comment]
@codersquid Or - if it's safe to use the edit button in prod, I could do that..

**Comment by codersquid** [comment]
It's probably safe. I will also copy the database regardless.

**Comment by polarbeardesign** [comment]
@katyhuff Yes you can edit that box in production. Or, if you feel more comfortable, send me what you would like to have in there and I can add it.

**Comment by katyhuff** [comment]
Gotcha. I'll do that tonight and close this when it's done! Thanks folks!

**Comment by katyhuff** [comment]
That did the trick. Thanks folks.
