### ISSUE TITLE
More options for reviewers

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#56]
Currently, all reviewers are asked to submit a single answer about each abstract. Namely, -1, -0, +0, and +1 are the options. That really isn't enough resolution to place an abstract.

Last year, we had much greater resolution for reviewer feedback and it really helped with things. Can we add some more resolution? Here is a link to last year's review form https://docs.google.com/forms/d/1LBIdJY8qXZRVgL7Qau3HU1W9hPmuTPuRPmjHOfoKH5M/viewform . 

 For each abstract, the reviewers were asked to fill this out once. It addressed everything we, as the program chairs, need to know with greater resolution, allowing us to more appropriately select between similar abstracts. The reviewer name and abstract title part can be skipped.

**Comment by mrterry** [comment]
I'm going to look into this, but it might require a shiney new review model.  We're running stock symposion right now and I don't know how hard it will be to swap out review models.  I'm going to look into this, though.

**Comment by katyhuff** [comment]
Thanks @mrterry !

**Comment by aterrel** [comment]
@katyhuff We looked at this and it seems we won't have enough time to get it done.  We can have a script that extract the information for each talk and populates a spreadsheet for you but that is about all I think we can promise here.  Sorry.

**Comment by katyhuff** [comment]
I'm sorry I don't totally understand what you're suggesting. The need is
something like my google form, which has its own script already. Are you
suggesting to embed that in the website somehow?

That is, I don't under stand what information you mean: Your script would
extract which information for each talk? The review information or
the abstract information?

On Tue, Mar 11, 2014 at 7:11 PM, Andy R. Terrel notifications@github.comwrote:

> @katyhuff https://github.com/katyhuff We looked at this and it seems we
> won't have enough time to get it done. We can have a script that extract
> the information for each talk and populates a webpage for you but that is
> about all I think we can promise here. Sorry.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/56#issuecomment-37368812
> .

## 

http://katyhuff.github.com

**Comment by aterrel** [comment]
Sorry for the lack of clarity.

We aren't able to get this integrated with symposion (the backend running the conf site) in the needed time.  We could set up the form in google forms and extract the talk data from the symposion  to populate the google forms.  We could probably script the reviews to go back to symposion from google docs as well.

**Comment by katyhuff** [comment]
Too bad. That works fine though. Thanks!

**Comment by katyhuff** [comment]
Ok, so.. since reviews start in one week, we need to at least make the review interface link to a google form so that reviewers can put in more detailed reviews.

If I make a new, blank, google form, who can do link to it on the site (in place of the current +/- 1 review option).

Also, how are the abstract writers meant to gain access to the review comments about their submissions? That is, will symposion facilitate the communication of review comments to the abstract authors? Last year, long form comments were part of the google form and we emailed everyone their review comments. If symposion has a better method, we should leave the review comment blocks in the symposion form. Else, we should take those out and do everything like we did last year. Thoughts?

Also my first github selfie, on my couch in my pjs:

![selfie-3](http://i.imgur.com/uojM6TQ.png)

**Comment by aterrel** [comment]
I can look into the interface. The hope would be that we can just have the comments uploaded to the symposion site which would then email the participants.

**Comment by katyhuff** [comment]
Here is the link to the actual form that we'll be using : https://docs.google.com/forms/d/1wa1th-8ALQA_7tdkOshOBK_uC1OrlM0ug7-V5FyXBuc/viewform

If sometime in the next day or two the review interface could be updated to send the reviewers to this link for each review, that would be way awesome. 

Thanks!

**Comment by katyhuff** [comment]
Ping! Hi folks. We would like the reviewers to start their reviews tomorrow. 
It would be great if the review interface either included all of the questions in our google form, or just linked straight to the google form.

This is what the review interface currently looks like:
![image](https://cloud.githubusercontent.com/assets/393899/2599556/4acce226-bae5-11e3-8893-b723afa1686f.png)

**Comment by codersquid** [comment]
I can quickly add a link to the form. I'll see if adding other content is something that can be done quickly or not.

**Comment by codersquid** [comment]
I added a link to the form and some content so that people will know what content they should be prepared to add when they get to the form. The template styling isn't honoring html markup, but I thought perhaps you'd like to have the link and content up quickly. We can see about fixing styling later.

Please take a look and see if I should fix anything. I took the liberty of deploying it quickly.

I'd like to know if this sentence is accurate:

  Your votes and comments are not public and will only be viewable by other reviewers.

**Comment by codersquid** [comment]
Also, I suppose we could remove the fields from the template so that there is no option to leave review comments in the form, but I thought perhaps it would be helpful for communicating with the authors.

**Comment by katyhuff** [comment]
In terms of review  comments on the site -  it would be great to leave
those blanks there if there is an easy way to send that info to authors
through Symposion.

I don't know what the steps are for emailing all the authors their review
comments via symposion ,  but if there's  a way,  let's do that. Do you
understand how to Emil all the authors that info when  we ultimately decide
on their paper?

**Comment by katyhuff** [comment]
As far as the sentence:
Your votes and comments are not public and will only be viewable by other
reviewers

That seems to be true.

The symposion framework makes the reviews of all papers visible to all
other reviews.  There is only one exception. That is, if there is a
reviewer who is also an author, then they can't see the  reviews of their
own submission.

**Comment by codersquid** [comment]
I don't know the ins and outs of symposion, but I think it does.

For the non-public except to other reviewers, I was wondering if it is also true for the form. Otherwise I'll clarify the sentence to distinguish symposion input vs. form input.

**Comment by katyhuff** [comment]
Well, with the form, no one sees the responses except for Serge and Andy
and I. Not even other reviewers.

On Thu, Apr 3, 2014 at 8:53 AM, Sheila Miguez notifications@github.comwrote:

> I don't know the ins and outs of symposion, but I think it does.
> 
> For the non-public except to other reviewers, I was wondering if it is
> also true for the form. Otherwise I'll clarify the sentence to distinguish
> symposion input vs. form input.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/56#issuecomment-39468481
> .

## 

http://katyhuff.github.com

**Comment by katyhuff** [comment]
We fixed this with a google form. Next year, maybe we'll do it in symposion.

**Comment by codersquid** [comment]
Maybe it's something for 2015.
