### ISSUE TITLE
mail is not being sent out on staging symposion site

### ISSUE THREAD

**Issue by codersquid** [scipy-conference/SciPy-2014#6]
Mail is not getting sent out to new users. We likely need to change settings.

**Comment by brettrmurphy** [comment]
The list in iContact is getting additional contacts. Is there a welcome message that isn't getting sent to them?

**Comment by codersquid** [comment]
Hi @brettrmurphy I'm currently troubleshooting this on the site we've set up on for staging. I can create users, and when I go through the password recovery process, I don't get email. I'm betting that we have not configured django-user-accounts or perhaps the email backend properly, and I am troubleshooting that tonight.

Do you have settings files for what you've been running that you are able to share with  me?

**Comment by brettrmurphy** [comment]
I don't have those. Sorry. Jim would be the guy to check with.

Brett

On Tuesday, December 10, 2013, Sheila Miguez wrote:

> Hi @brettrmurphy https://github.com/brettrmurphy I'm currently
> troubleshooting this on the site we've set up on for staging. I can create
> users, and when I go through the password recovery process, I don't get
> email. I'm betting that we have not configured django-user-accounts or
> perhaps the email backend properly, and I am troubleshooting that tonight.
> 
> Do you have settings files for what you've been running that you are able
> to share with me?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/6#issuecomment-30286188
> .

## 

Brett Murphy
Enthought, Inc.
bmurphy@enthought.com
512-536-1057

**Comment by polarbeardesign** [comment]
I think Brett is referring to a email service, iContact, that SciPy is using to send updates to subscribers (for SciPy2014 info). 

That is separate from the email service Django/symposium is using for users creating SciPy2014 accounts on the website. 

Does that make sense?

Jim

**Comment by codersquid** [comment]
Things make sense now. I was confused, but trying to roll with it.

**Comment by codersquid** [comment]
It turns out this was from a combination of things. We didn't have all of the django mail settings, and we also didn't have a cron job set up to call the [django-mailer](https://pypi.python.org/pypi/django-mailer/0.1.0) commands.

**Comment by codersquid** [comment]
I need reviewers to help. Currently on staging I added a crontab for the scipy user which calls a script I created as a wrapper around the django command. The script handles activating the virtualenv.

```
# m h  dom mon dow   command
* * * * * (/home/scipy/site/bin/django_mail.sh send_mail >> /home/scipy/site/logs/cron_mail.log 2>&1)
0,20,40 * * * * (/home/scipy/site/bin/django_mail.sh retry_deferred.sh >> /home/scipy/site/logs/cron_mail.log 2>&1)
```

```
#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: django_mail.sh <send_mail|retry_deferred>"
    exit
fi

MAILCMD=$1
case "$MAILCMD" in
    send_mail) ;;
    retry_deferred) ;;
    *) echo "invalid option: $MAILCMD"; exit ;;
esac


set -e
VERSION="20131204"
VIRTUALENV=/home/scipy/venvs/scipy$VERSION
DJANGODIR=/home/scipy/site/SciPy-2014/
DJANGO_SETTINGS_MODULE=scipy2014.settings
DJANGO_WSGI_MODULE=scipy2014.wsgi

echo "Starting django-mailer: $MAILCMD"
echo "Activating $VIRTUALENV"
source ${VIRTUALENV}/bin/activate

cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

./manage.py $MAILCMD

echo "done with django-mailer: $MAILCMD"
```

**Comment by mrterry** [comment]
i'm looking at this now.  I just got an email as an additional speaker.

the links in the email are wrong, but babysteps.

**Comment by mrterry** [comment]
The venv in the script should be updated with each deploy.  Yes?

**Comment by codersquid** [comment]
Create a new venv per deploy, I think.

**Comment by mrterry** [comment]
right.  but the email script should point to the same venv as the website.  it should not perpetually point to 20131208.

**Comment by codersquid** [comment]
With the fabfiles you made we can have a template for this or perhaps just
call sed from the script. Without the fabfile we have to resort to editing
it manually.

**Comment by mrterry** [comment]
done
