### ISSUE TITLE
Make a page with all the announcements for people who miss them

### ISSUE THREAD

**Issue by jonathanrocher** [scipy-conference/SciPy-2014#62]
It would be useful to have a page with all the announcements that went out publicly for people who don't follow lists and/or will arrive later in the game...

**Comment by aterrel** [comment]
@jonathanrocher Can you make a blog post? Instructions at: https://github.com/scipy-conference/conference.scipy.org

The website has info on the about page but I agree we need more details to be found.  https://conference.scipy.org/scipy2014/about/

**Comment by jonathanrocher** [comment]
Will do.

**Comment by aterrel** [comment]
@jonathanrocher Okay the announcement post went out.  Can you make sure it appears on Planet Python and Planet SciPy.  I've emailed those lists before but they are always a bit slow getting things setup ....

The feed is at http://conference.scipy.org/feeds/all.atom.xml

**Comment by jonathanrocher** [comment]
I have no idea how to do that. A pointer would be appreciated unless @scopatz wants to take care of that...
