### ISSUE TITLE
Add important dates on the front page

### ISSUE THREAD

**Issue by jonathanrocher** [scipy-conference/SciPy-2014#63]
Dates can be found in 
https://github.com/scipy-conference/scipy-conference/blob/master/mailings/conference_announcement.rst

**Comment by aterrel** [comment]
@polarbeardesign can we get one of the cards have important dates.

Would also be good to add contact info as well:

scipy-organizers@scipy.org
"@scipy-conf" -> Twitter
+ScipyConference -> G+

**Comment by aterrel** [comment]
Okay I see we just need to add the email list. I'll put this in another issue.

**Comment by polarbeardesign** [comment]
added
