### ISSUE TITLE
Add a banner reminding people that abstract submission is open until March 14th

### ISSUE THREAD

**Issue by jonathanrocher** [scipy-conference/SciPy-2014#64]
Last year we had a yellow banner for people not to be able to miss that piece of information...

**Comment by katyhuff** [comment]
This should involve also, putting the call somewhere on the website...

On Wed, Feb 19, 2014 at 3:24 PM, Jonathan Rocher
notifications@github.comwrote:

> Last year we had a yellow banner for people not to be able to miss that
> piece of information...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/64
> .

## 

http://katyhuff.github.com

**Comment by aterrel** [comment]
done
