### ISSUE TITLE
Add better instructions on submitting proposal

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#69]
From @brettrmurphy:

"""It's really hard to tell what to do to submit a paper. At least: how about a button under  the deadline announcement in the upper right that links to the sign in page (I assume that's the first step?) Even better would be a pull-down menu next to Sponsors, named Speaking, that describes the speaking opportunities and invites them to submit. PyCon has this."""

**Comment by katyhuff** [comment]
I just wanted to bump up the importance of this. 

A couple of folks (who are very capable of navigating websites) have asked me how to do this. I think Brett's suggestion is right on. Whether you're logged in or not, there should be at least some indication that we're accepting submissions. I really like Brett's pull down menu solution. And, if that's too complicated I agree that there should, at the very least, be a button on the main page like "speakers" or that says "Submit an Abstract". That button should direct the user to log in and should take them to the "Submit-A-Proposal > Talks-and-Posters" page.

As it is, I give them the following 5 step instructions. 
1) log in
2) go to dashboard 
3) click "submit proposal"
4) click on talks and posters
5) click "create new... "

(the first three steps of this process are not obvious at all to most people)

**Comment by polarbeardesign** [comment]
added Submit a Proposal! box to call/about page [https://conference.scipy.org/scipy2014/about/]

Considering adding "Speaking" nav item that points to same page - confusing (2 navigation items going to same page) or good idea?

**Comment by brettrmurphy** [comment]
I think having two routes to the same page is ok, FWIW.

-- Brett

Brett Murphy
Enthought, Inc.
bmurphy@enthought.com
512-536-1057
_Join us for a live webinar demo of our Python for Excel solution on March
6th.  Register here today
https://www1.gotomeeting.com/register/937020305._

**Comment by polarbeardesign** [comment]
I agree - adding it. If it proves confusing, it's easy enough to remove it.

**Comment by codersquid** [comment]
Adding a button on the main page could be an enhancement we could think about.

The `dashboard.html` template in symposion has a button that directs to a `proposal_submit` url. We could consider adding a link or button to the main page that carries people to this page. I haven't checked  the experience for someone who has not created a speaker profile or is not logged in. I'm hoping it wouldn't be too jarring to a user.

```
 <a href="{% url proposal_submit %}" class="btn">
  <i class="icon-plus-sign"></i> Submit a new proposal
</a>
```

**Comment by aterrel** [comment]
Please add card to front page.

**Comment by katyhuff** [comment]
Hi all - While this is going on, could it say "Talk Abstracts and Proposals" everywhere that the site currently says "Proposals"? I don't think "Submit a Proposal" is something I would click if I wanted to submit a talk abstract.

**Comment by polarbeardesign** [comment]
added card/tile to homepage
