### ISSUE TITLE
Account confirmation email gives wrong link

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#71]
I think this just started happening last night. I got an email about it this morning from one of our PC members who was signing up on the site.

---------- Forwarded message ----------
From: John Stachurski <...>
Date: Thu, Feb 20, 2014 at 10:47 AM
Subject: Fwd: Confirm email address for SciPy 2014 [local]
To: Katy Huff <...>
Hi Katy,

Just letting you know about a small error.  In the link below, "localhost" should be replaced by "conference.scipy.org".

Regards, John.

---------- Forwarded message ----------
From: webmaster@localhost
Date: Fri, Feb 21, 2014 at 12:20 AM
Subject: Confirm email address for SciPy 2014 [local]
To: <...>

A user on SciPy 2014 [local] has created an account using this email address.

To confirm this email address, go to http://localhost/scipy2014/account/confirm_email/8865f70c8e0970be561ff2f2ad890824e1e1d4bdd78e1d4555a55c7bb8e25313/

If you did not sign up for this site, you can ignore this message.

**Comment by katyhuff** [comment]
Hi Folks, I'm getting more emails about this error by the hour. I don't have the foggiest idea how to fix it. Do any of you? @mrterry @aterrel @polarbeardesign @codersquid ?

**Comment by aterrel** [comment]
Sorry for the spam. I won't have time to look at it until late tonight.

**Comment by katyhuff** [comment]
Thanks @aterrel ! I'm not bothered by the spam. I just feel bad for our confused PC members who are just trying to sign up for accounts because they're all getting a confirmation email that sends them to the wrong address.

**Comment by codersquid** [comment]
I'm confused about why this happens, because it does seem we have the proper SITE_ID in place for prod.

The mail template comes from pinax-bootstrap-theme,

```
{% load i18n account_tags %}{% blocktrans with site_name=current_site.name %}A user on {{ site_name }} has created an account using this email address.

To confirm this email address, go to {{ activate_url }}

If you did not sign up for this site, you can ignore this message.
{% endblocktrans %}
```

Check in the admin, the site name is _SciPy 2014_ and so on.

**Comment by katyhuff** [comment]
It's not the scipy2014 part that's a problem. 
It's the domain. 
The link is giving : 
http://localhost/scipy2014/ ... 
But it should be 
http://conference.scipy.org/scipy2014/...

Is the domain part of current_site.name?

**Comment by codersquid** [comment]
It was 162.242.221.143 and I just changed it to conference.scipy.org and tested out getting a new account. I got an email with the ip as the url.

SITE_ID 1 has
- domain: localhost
- name: SciPy 2014 [local]

Which is why I mentioned the name -- it's showing up with local in the reported email as well.

The prod local settings is not using SITE_ID 1. I don't know why SITE_ID 1's entries are getting used.

**Comment by katyhuff** [comment]
ah. hm. The ip as the url is probably better than localhost?

**Comment by codersquid** [comment]
Yes, better than localhost, but driving me crazy. Why isn't it using the domain from the sites setting? Andy might discover it later.

**Comment by aterrel** [comment]
Just needed a restart for gunicorn.

I also deleted the problematic sites that keep getting put up.
