### ISSUE TITLE
Add deadline and diversity question to financial aid page

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#96]
This was noticed by @pfrancislyon and is super urgent. The Financial Aid page of the SciPy web site needs a deadline (April 1) and another criterion added to the list of questions in the application template.

Any chance you could add those two things to the site: https://conference.scipy.org/scipy2014/participate/financial_aid/ ? Since it needs to be added in the next day or so, I'm hereby pinging all of you who know how to get this done (@mrterry , @codersquid , @aterrel ). Thanks!!!

Specifically, we need the deadline (april 1) to be listed prominently and we need one more piece of information from applicants asking the applicant to indicate yes or no if they want to be "Considered for women or underrepresented group scholarship:"

**Comment by codersquid** [comment]
On it

**Comment by codersquid** [comment]
I added a list point:
- Indicate yes or no to apply to be considered for women or under-represented group scholarship

and put the deadline info in the header with the abstract deadline info.

![deadline](https://cloud.githubusercontent.com/assets/529748/2560020/20c49e24-b79d-11e3-9c56-4c20de99251f.png)

Okay? I'll bug @aterrel @mrterry @polarbeardesign if they can make it look better. What do you think?

**Comment by katyhuff** [comment]
You rock. That rocks. Thank you sheila.

**Comment by codersquid** [comment]
Thanks! I'll push and then someone can refine the look more if needed.

**Comment by codersquid** [comment]
Change deployed.
