### ISSUE TITLE
Missing a track! 

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#99]
Sorry I have so many demands, y'all! 

I totally didn't notice this was missing until I got an email just now from the chair of that domain symposium, @davclark . We need a domain sympoisum option for "Computational Social Sciences and Digital Humanities". It's missing entirely in the talk submission form. Can it be added ASAP? 

Just so that everyone sees this issue, I'm going to ping you ( @aterrel @codersquid @mrterry @polarbeardesign ). Sorry! Hopefully it's not that hard.

**Comment by codersquid** [comment]
It doesn't look hard. Let me try...

**Comment by codersquid** [comment]
Okay, I've deployed the change. Check that it works for you. It looks okay on my end.

**Comment by katyhuff** [comment]
Perfect. 
You are the bomb. 
Seriously. https://www.youtube.com/watch?v=jorJh8DTMVM#t=1m18s
